text1 = "Welcome to Klymapo's Game Adeventure!\nYou are a young adventurer who has just arrived in the kingdom of Arya\nLet´s star with your charecter creation\n\n"


text2 = "You decide to enter the local tavern. In one corner, a dark wooden mission board catches your attention. You approach the board and find a interesting mission:\n\nThe Mystery of the Enchanted Forest: Strange lights have been seen in the heart of the Shadow Forest. You study the mission carefullY and decide to go to mission \n"


text3 = "Before heading to the Forest of Shadows, you decide to visit the village's weapon shop to equip yourself better. You have a small leather bag with about 100 gold coins, enough to purchase one item."


text4 = "Once in the forest, you encounter a group of small, fierce creatures known as Kobolds. You know that you have your new weapon prepare for combat. But the offensive is not always the best option"


text5 = "Instead of fighting, you raise your hands in a gesture of peace and say, ‘Wait, can’t we solve this by talking?’\nThe kobolds, an armed patrol, stop, surprised. The leader, with a grimace of disgust, says, ‘Why should we trust a human?’?\n‘We can waste time fighting, or you can go on your way,’ you respond calmly. ‘Besides, there are surely more important things to do than this pointless fight.’\nAs you speak, you pull a couple of coins from your pouch and offer them. ‘Take this as a gesture of goodwill.’\nReluctantly, the leader lowers his weapon and takes the coins. ‘Alright, human, we don’t have time for this.’\nWithout further words, the kobolds hastily leave, casting distrustful glances as they disappear into the trees, leaving the conflict behind and you with the feeling of having avoided an unnecessary battle."


text6 = "Instead of fighting, you raise your hands in a gesture of peace and say, ‘Wait, can’t we solve this by talking?’\n\nThe kobolds, an armed patrol, stop but their eyes narrow with suspicion. The leader, sneering, says, ‘Why should we trust a human?’\n\n‘We can waste time fighting, or you can go on your way,’ you respond, trying to stay calm. ‘Besides, there are surely more important things to do than this pointless fight.’\n\nAs you speak, you pull a couple of coins from your pouch and offer them. ‘Take this as a gesture of goodwill.’\n\nThe leader looks at the coins with contempt. ‘We’re not interested in your bribes, human,’ he says, his voice filled with disdain. ‘You’ve wasted our time.’\n\nThe kobolds advance, weapons drawn, and the air crackles with tension. Despite your efforts, it seems that the conflict is inevitable, and you brace yourself for the fight to come, feeling a sense of frustration at having failed to prevent it."

text7 = "As you accidentally stumble upon the kobolds in the forest, you don’t hesitate and immediately launch an attack.\n\nThe kobolds, caught off guard by your sudden aggression, scramble to ready their weapons. The leader, eyes wide with shock, growls, ‘So it’s a fight you want!’\n\nWithout wasting any time, the kobolds rush toward you, and the clash of steel fills the air. You engage in battle, fueled by the surprise and urgency of the situation. The forest around you becomes a chaotic battleground as you face off against the kobolds, driven by the need to defend yourself."

text8 = "Seeing the kobolds, you quickly decide to flee and turn to run through the forest.\n\nThe kobolds, momentarily surprised by your sudden dash, hesitate just long enough for you to gain distance. You weave through the trees, using your knowledge of the terrain to your advantage.\n\nAfter a tense chase, you manage to lose the kobolds among the dense foliage. Safe for now, you catch your breath and reflect on the narrow escape, relieved to have avoided a potentially dangerous confrontation."

text9 = "Seeing the kobolds, you attempt to flee, but they quickly react to your movement.\n\nDespite your efforts, the kobolds are fast and determined, cutting off your path and forcing you to a halt. The leader sneers and says, ‘There’s no escape, human. You’ll have to face us.’\n\nCornered and outnumbered, you brace yourself as the kobolds advance, weapons drawn. The battle is inevitable, and you steel yourself for the fight that’s about to unfold, knowing there’s no way to avoid it."

batlle = "As soon as you see the kobolds, you draw your weapon and charge at them, catching them off guard. The leader snarls, rallying his troops to fight back. Blades clash and shouts echo through the forest as the kobolds swarm around you, their weapons glinting in the dappled sunlight.\nYou skillfully parry their blows, countering with swift, precise strikes. One kobold lunges at you, but you sidestep and bring your sword down, felling him with a single blow. Another comes at you from the side, but you spin and deflect his attack, responding with a powerful slash that sends him to the ground.\nThe leader, seeing his comrades fall, roars in fury and charges at you. The two of you exchange fierce blows, but your determination and superior skill prevail. With a final, decisive strike, you bring the leader down.\nAs the last kobold collapses, you survey the battlefield, catching your breath. The fallen bodies of the kobolds lie scattered around you, a testament to the intensity of the fight.\nWith the threat neutralized, you decide to continue on your path, venturing further into the forest with your focus on your own journey.\nYou move deeper into the woods, leaving the encounter behind and pressing forward with determination."

text10 = "Once the matter with the kobolds is settled, you decide to continue on your path, venturing further into the forest with your focus on your own journey.\nYou move deeper into the woods, leaving the encounter behind and pressing forward with determination.\nSuddenly, a huge spectral wolf appears before you, its eyes glowing with an ethereal light.\nHowever, you notice that its behavior is strange; it seems more frightened than aggressive.\nYou prepare to defend yourself, but then a comical, lanky figure emerges from the trees.\n'Stop, stop! Don't hurt him!' shouts the figure, a gnome with crooked glasses and a faded robe.\n'He's my friend, Luzbel. He's here to help me with my magical light experiments!'\nThe gnome, who introduces himself as Fizzlewop, explains that the lights and the wolf's behavior are due to his experiments with magical crystals.\nThe villagers mistook the experiments for a threat.\nYou pause, considering whether to believe Fizzlewop or not."

text11 = "Fizzlewop, feeling guilty for the misunderstanding, offers you a reward.\n'Thank you for not harming Luzbel and for your bravery. Take this; it's a special sword,' he says as he hands you a small, ornate weapon.\n'I call it... the Sword of Celestial Light!'\nYou examine the sword and notice that despite its impressive name, it's of low quality.\nHowever, you appreciate the gesture and know it will be useful in your adventures.\nYou thank Fizzlewop and return to the village to inform them that everything is fine.\nThe villagers greet you with joy and relief, and although the sword isn't the most powerful, you feel you've made a new friend and brought peace to the Shadow Forest."

text12 = "You decide not to trust the gnome's explanation and keep your weapon ready.\n'I don't believe you,' you say firmly, eyeing the spectral wolf warily. 'Prove that this creature is harmless.'\nFizzlewop looks disheartened but nods. 'Very well, I can show you,' he says, pulling out a small crystal from his robe. He mutters an incantation, and the spectral wolf's form shimmers, then solidifies into a harmless, docile creature.\n'You see, he truly is my friend,' Fizzlewop says, his voice pleading. Reluctantly, you lower your weapon, still cautious but convinced by the display.\n'Thank you for giving me a chance to prove myself,' Fizzlewop says. 'As a token of my appreciation, please take this.' He hands you a small, ornate weapon. 'I call it... the Sword of Celestial Light!'\nYou examine the sword and notice that despite its impressive name, it's of low quality.\nHowever, you appreciate the gesture and know it will be useful in your adventures.\nYou thank Fizzlewop and return to the village to inform them that everything is fine.\nThe villagers greet you with joy and relief, and although the sword isn't the most powerful, you feel you've made a new friend and brought peace to the Shadow Forest."